chrisj117/CS-472-GROUP-2-PROJECT

data/UNLV Courses/courses.csv
data/UNLV Courses/scrape.py

_**WHAT DOES THIS PR DO?**_
- Adds a directory ```data``` to the project which contains a sub directory, ```/UNLV Courses```. This folder contains ```scrape.py``` which was used to scrape the unlv course webpage for all current courses and load them into a csv. The resulting csv of this program is stored in the same folder.
- ```courses.csv``` will be used to load a Django model for UNLV Courses.
_**WHAT ISSUES ARE RELATED TO THIS PR?**_
- gh-22 
- Simply running ```scrape.py``` with the required libraries installed will create a new (identical) courses.csv file.
**_ADDITIONAL CONTEXT_**
- The folder structure I put the data in is not purposeful, it can be arranged and changed for however we see best for the project.

Created UNLV Course CSV, Included scrape.py

---

web/package-lock.json
web/package.json
web/postcss.config.js
web/src/App.jsx
web/src/components/Content.jsx
web/src/components/Navbar.jsx
web/src/components/Searchbar.jsx
web/src/index.css
web/src/main.jsx
web/src/pages/Home.jsx
web/src/pages/NotFound.jsx
web/tailwind.config.js

- This PR updates the frontend dependencies that we will use to style the UI of the application. This includes Tailwind CSS, React Icons, and React Router Dom. It also removes React Bootstrap which is being replaced with Tailwind.
- #17 
- You can now import React-Icon components, use Tailwind CSS in class names, and use React Router to create routes to different page components.

Update Frontend Dependencies

---

.github/ISSUE_TEMPLATE/general-issue-template.md

- Adds an issue template to the repository following the steps outlined in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
- #24 
- Upon making an issue, the template should be available to users.

Created basic issue template

---

docs/pull_request_template.md

- Adds an pull request template to the repository following the steps outlined in https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
- #24 
- Upon making an pull request, the template should be available to users.

Created pull request template

---

web/src/pages/Home.jsx

- This PR focuses solely on setting up the appearance of the Home page
- Search functionality and page routing is **not** included
- #20 
- #4 
- Run this project locally
- Upon loading, the following page should appear:

Home Page Appearance Setup

---

web/src/main.jsx
web/src/pages/Home.jsx

- This PR replaces instances of `class` with `className` in `web/src/pages/Home.jsx` in order to follow proper JSX syntax relating to the class attribute.
- This PR imports `Home` component into `web/src/main.jsx` and sets it as the index page within `router` variable.
- https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/issues/47
- Run this project locally.
- Accessing `http://localhost:5173/` should now bring you to our website's homepage.

Clean up JSX syntax in Home.jsx and set it as index page of website

---

web/src/components/Navbar.jsx
web/src/pages/RequestSchool.jsx

- This PR creates a simple navbar (`web/src/components/Navbar.jsx`) that can be added to the top of pages. It consists of the site name in the top left corner which will take you back to the home page. In the top right corner are a "Light Mode" button (functionality has not been implemented yet), as well as links to the About page and Request School page.
- This PR also creates a skeleton for a request school page (`web/src/pages/RequestSchool.jsx`). It consists of a field to see if your school is already in the database as well as a form to request for a new school to be added. The form functionality has not yet been implemented. Only the HTML elements are present.
- …

Created navbar and request school page

---

web/src/pages/About.jsx

- This PR sets up the "About" page's appearance and functionality
- "Return to home" button and "About" content implemented
- #45 
- Run this project locally
- Navigate to the "About" page with the Navigation Bar or go to http://localhost:5173/about
- Upon loading, the following page should appear:
- Clicking on the "Return to home" button should return the user to the home page

About Page Setup

---

web/src/components/Navbar.jsx

_WHAT DOES THIS PR DO?_
- Replace the a attributes with the Link router
_WHAT ISSUES ARE RELATED TO THIS PR?_
- #44 
_HOW DO I TEST OUT THIS PR?_
- cd to 'web' directory
- run the command 'npm run dev'
- go to the website
- click on 'About' on the top-most navigation bar to go to the about page 
- click on 'Request a School' on the top-most navigation bar to go to the request a school page
- click on 'MyCourseEvaluation' on the top-most navigation bar to return to the home page

creat link components

---

web/src/components/QA.jsx
web/src/pages/Home.jsx

- This PR removes the redundant navbar that was hard-coded into the home page.
- This PR creates a Question-Answer component (`web/src/components/QA.jsx`) which is used to structure the FAQ section of the home page. This component replaces the hard-coded FAQ section with a simpler component-based approach using props to fill in the specific questions and answers.
- https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/issues/44
- Run this project locally.
- Accessing `http://localhost:5173/` should show the updated home page without the redundant navbar. The FAQ section should look the same, indicating that the refactoring of the FAQ section did not disrupt the appearance of the home page.

Home Page: Removed redundant navbar & created Question-Answer component

---

web/src/components/Navbar.jsx
web/src/components/ReturnHome.jsx
web/src/pages/About.jsx
web/src/pages/NotFound.jsx

- Created "Not Found" page (`web/src/pages/NotFound.jsx`) that displays error message along with a button that returns the user to the home page when clicked. This page also includes the navbar at the top.
- Created `ReturnHome` component in (`web/src/components/ReturnHome.jsx`) which is a button that returns the user to the home page when clicked. This component is based on the button previously implemented directly in the About page.
- Updated About page to use the new `ReturnHome` component.
- Fixed a bug that made the Light Mode button into a link that redirected the user to the home page.
- https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/issues/58
- Run the project locally.
- …

Created "Not Found" page

---

web/src/pages/RequestSchool.jsx

_WHAT DOES THIS PR DO?_
- Updates the previous placeholders in the 'web/src/pages/RequestSchool.jsx'
_WHAT ISSUES ARE RELATED TO THIS PR?_
- #46 
_HOW DO I TEST OUT THIS PR?_
- Run locally 
- Click on 'Request a School' on the topmost navigation bar to go to the 'request a school' page
- See the new placeholders

Updating Request School Page

---

CONTRIBUTING.md
docs/PR-CHECKLIST.md

- This PR uploads PR review guideline to the repo
**_WHAT ISSUES ARE RELATED TO THIS PR?_*
- #76 
- Just look for `PR-CHECKLIST.md` in `/docs` directory

Upload PR Review Guideline to Repo

---

web/.eslintrc.cjs
web/src/components/CourseCard.jsx
web/src/components/QA.jsx
web/src/components/Searchbar.jsx
web/src/components/SquareRating.jsx
web/src/main.jsx
web/src/pages/Home.jsx
web/src/pages/School.jsx

- Creates the school page skeleton design
- The page will have mock data that will later be replaced by actual course information from the database
- It establishes a temporary URL in the routing section of `main.jsx` for the purpose of testing
- Adds a course search bar to the top of the page
- #4  
- #61 
- Visit http://localhost:5173/school

School Page Features 1

---

web/.eslintrc.cjs
web/package-lock.json
web/package.json
web/src/components/CourseCard.jsx
web/src/components/QA.jsx
web/src/components/RatingBar.jsx
web/src/components/ReviewCard.jsx
web/src/components/Searchbar.jsx
web/src/components/SquareRating.jsx
web/src/main.jsx
web/src/pages/Home.jsx
web/src/pages/Review.jsx
web/src/pages/School.jsx

- Added a rating component that will work on the course page eventually, but currently with mock data
- Does not complete the course page
- Adds headings to the main sections of the course page
- #43
- Visit `http://localhost:5173/review` to check it out

Course Page Features 2

---

api/backend/settings.py
api/backend/wsgi.py
api/build.sh
api/vercel.json

- In this PR, we implement continuous deployment  of the API using Vercel. 
- #95 
- Once deployment is successful, a deployment URL will be available to access the API endpoints

[deploy] Continuous Deployment of Backend API using Vercel

---

web/src/components/Navbar.jsx
web/src/main.jsx
web/src/pages/Login.jsx
web/src/pages/Register.jsx
web/src/pages/SignUp.jsx

- Creates empty pages for login and registration
- Adds routes for routing to the pages
- Adds links to navbar for quick access
- #101 
- Run `npm run dev` to start the local dev server. Go to the url `http://localhost:5173/login` or `http://localhost:5173/register` to see the newly creates pages on their respective routes

Frontend Authentication Setup

---

web/src/pages/Login.jsx

- Adds a login page for the website (no functionality implemented)
- https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/issues/99
- Run this project locally (`cd` to `web` directory and then run `npm run dev`)
- Navigate to the login page by clicking `Login` on the homepage navbar
- Upon loading, the following page should appear:

Create Login Page

---

web/src/pages/Register.jsx

- This PR creates the account Registration page's appearance (no back end functionality implemented)
- "Password complexity" message is tentative
- Back end password/e-mail/username checking is not implemented
- #100 
- Run this project locally (navigate to the `web` directory, run `npm i` then `npm run dev`)
- Navigate to the "Register" page by going to http://localhost:5173/register
- Upon loading, the following page should appear:

Create Registration Page

---

web/src/components/Navbar.jsx

- Updates the navbar to be responsive on different resolutions
- Updates full logo to only icon when on mobile screen
- Adds hamburger button to open mobile navigation menu
- Adds close button to close mobile navigation menu
- #103 
- #104 
- #107 
- #106 
- #105 
- Fetch the branch `navbar-mobile-sidebar`
- Run `npm run dev` in the `web` directory, and open inspect element to check the different resolutions by changing the dimensions to "responsive" mode. You will be able to use the hamburger menu to control the nav bar.

Responsive Navbar and Hamburger Menu

---

web/src/components/InputField.jsx
web/src/pages/Login.jsx
web/src/pages/Register.jsx

- Creates the InputField JSX component to represent the input fields on the Login and Register pages.
- Refactors the Login and Register pages to use the InputField component.
- https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/issues/119
- Test this PR locally
- `cd web` and then when inside the `web` directory, run `npm run dev`
- Access the website using `http://localhost:5173/`
- Navigate to the register and login pages using the navbar. The pages should look the same as before, it's just that the code that implements the pages is now shorter and more concise.

InputField component for tidying up Login & Register pages

---

api/Dockerfile
api/authentication/views.py
api/backend/settings.py
api/build.sh
api/requirements.txt
api/vercel.json

- The current API deployment is unstable and this PR is intended to resolve the issue
- #96 
- This can only be test after it has been success deployed. I am currently this by forking and create a deployment on my personal vercel account

FIX: Api deployment

---

api/authentication/views.py

- Remove static username from the registration welcome message
N/A

Hot-Fix: Static Username in Registration Message

---

web/src/components/FormError.jsx
web/src/components/FormSuccess.jsx
web/src/components/Navbar.jsx
web/src/main.jsx
web/src/pages/About.jsx
web/src/pages/Home.jsx
web/src/pages/Login.jsx
web/src/pages/NotFound.jsx
web/src/pages/PasswordReset.jsx
web/src/pages/Profile.jsx
web/src/pages/Register.jsx
web/src/pages/RequestSchool.jsx
web/src/pages/Review.jsx
web/src/pages/Root.jsx
web/src/pages/School.jsx
web/src/utilities/Auth.jsx
web/src/utilities/AuthProvider.jsx
web/src/utilities/ProtectedRoute.jsx
web/src/utilities/UnProtectedRoute.jsx

- Fixes registration bugs
- Fixes login bugs
- Adds error handling for login
- Adds profile popup for logged in users
- Protects login and registration routes if signed in
- Creates and protects profile route
- Adds link if forgot password on login page (but no route yet)
- Adds loading phases for login, registration, logout
- Adds auth check on review page
- Fixes styling issues related to navbar
- #43 
- #99 
- #43 
- #101 
- #131 
- Make sure the local server is running using `python3 manage.py runserver` in the `api` directory. Head over to the `web` directory and run `npm i` and `npm run dev` to run the frontend. You can test the registration by going to login, clicking "Create an …

Frontend Auth Completed

---

web/src/pages/About.jsx

- Fixes some padding and font-size issues on the About Page so it displays nicely on mobile screens.
- Before: (iPhone 12 Pro - 390x844 dimensions)
- After: (iPhone 12 Pro - 390x844 dimensions)
- https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/issues/126
- Run the project locally
- `cd web` then `npm run dev`
- Go to http://localhost:5173/ in your web browser
- Navigate to About Page and then inspect the page
- Toggle the device toolbar and switch to iPhone 12 Pro dimensions
- Updated About Page should appear

About Page Mobile Responsiveness

---

api/build.sh

- Uploading course data during deployment 
- N/A

Hotfix: Upload course data

---

.github/workflows/ci.yaml

- Display code coverage for both frontend and backend 
- Codecov dashboard

Hotfix: Codecov

---

web/src/components/Searchbar.jsx
web/src/components/example.jsx
web/src/main.jsx
web/src/pages/Course.jsx
web/src/pages/Home.jsx
web/src/pages/Login.jsx
web/src/pages/PasswordReset.jsx
web/src/pages/Profile.jsx
web/src/pages/Register.jsx
web/src/pages/RequestSchool.jsx
web/src/pages/Root.jsx
web/src/pages/School.jsx
web/src/tests/regexTest.test.js
web/src/utilities/API.jsx
web/src/utilities/GetData.jsx
web/src/utilities/RegexTest.jsx

- Sets up the request school endpoint interaction
- Allows users to search from the home page now
- Sets ups loaders so that accessing incorrect endpoint takes you to 404 page
- Corrects state management
- Adds school search functionality on request school page
- #4 
- #3 
- #142 
- Make sure the local server is running using `python3 manage.py runserver` in the `api` directory. Head over to the `web` directory and run `npm i` and `npm run dev` to run the frontend. You can test the request school form by going to `request-school` and filling in the information and submitting. You can search for schools from the home page.

Searchbar & Request School 1

---

api/.env-example
api/UNLV_course_data/courses_with_professors.csv
api/backend/urls.py
api/school/.env-example
api/school/serializers.py
api/school/views.py

- Returns list of courses and professors
- #149 
- Checkout this branch locally and `cd` to `api/` directory
- Run `pip install -r requirements.txt`
- Run `python manage.py runserver`
- Go to `http://localhost:800`
- Test the endpoint: `{base_url}/school/{short_name}/courses

Add courses endpoint

---

web/src/pages/Login.jsx
web/src/pages/Register.jsx

- Adds mobile responsiveness functionality to the login and register page
- Dark mode cutoff is avoided in this implementation too
- Example mobile preview of login page:
- #127 
- #128
- To locally test this branch, checkout this branch and navigate to web directory: ```CS-472-GROUP-2-PROJECT/web```
- Run ```npm run dev```
- Go to the local pages to see changes 
- For login page: ```http://localhost:5173/login```
- For register page: ```http://localhost:5173/register```
**_ADDITIONAL COMMENTS_**
- I am unfamiliar with frontend development, especially tailwind, let me know if any issues stand out and need to be fixed!

Login + Register Page Responsiveness

---

web/src/components/CourseCard.jsx
web/src/components/Searchbar.jsx
web/src/index.css
web/src/main.jsx
web/src/pages/Home.jsx
web/src/pages/RequestSchool.jsx
web/src/pages/Root.jsx
web/src/pages/School.jsx
web/src/utilities/GetData.jsx

- Changes styles of search bars and input fields in multiple places
- Changes styles of search bars in dark mode
- Updates search format in school page
- Updates courses in school page based on search
- Change course card info to make it simpler
- Adds mobile responsiveness for school page
- Adds search icons to search bars
- Adds 3 layer filtering to the courses
- #4 
- #141 
- #108 
- #61 
- #107 
- Make sure the local server is running using `python3 manage.py runserver` in the `api` directory. Head over to the `web` directory and run `npm i` and `npm run dev` to run the frontend. You can test the filtering by searching a school (UNLV) and typing in some course name. This filters by …

Searchbars & School Page Complete

---

web/src/pages/Review.jsx

- Updates the 'Course Professor' dropdown and the 'Written Evaluation' dropdown text to make it visible in dark mode
- #158 
- cd to the web directory and do 'npm run dev'
- go the website and add '/review' to the end of the URL
- switch to dark mode on the review page
- you should see the both dropdown texts are now visible

Updated Review.jsx Dropdown Text

---

web/package-lock.json
web/src/components/CourseCard.jsx
web/src/components/RatingBar.jsx
web/src/components/ReviewCard.jsx
web/src/components/Searchbar.jsx
web/src/main.jsx
web/src/pages/Home.jsx
web/src/pages/Review.jsx
web/src/pages/School.jsx
web/src/utilities/Axios.jsx
web/src/utilities/GetData.jsx

- Allows user to post reviews
- Fixes professor dropdown
- Touches up on styling for review page
- Changes API key for production
- #43 
- #8 
- Go to our deployment and post a review for a class

Final Touchups & Deployment

---

api/backend/settings.py

- Fixing CORS error
- N/A
- n/a

chore: fix cors error in production

---

web/src/components/ReviewCard.jsx
web/src/pages/Review.jsx
web/src/utilities/PostData.jsx

- Implements the functionality for the rating button in the Review component.
- Enables real-time updating of review helpfulness ratings, allowing users to like or dislike reviews.
- Adds logic to prevent users from rating the same review multiple times.
- Integrates user authentication to ensure that only logged-in users can rate the reviews.
- In the browser, go to the Review page of any course.
- Test the rating button functionality by liking or disliking a review.
- Observe that the count updates accordingly and prevents re-rating by the same user.
- Log out and attempt to rate a review to ensure it prompts for user authentication.

Review Rating Button
